version: "3.7"
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
      target: run-app
    environment:
      - SERVER_PORT=80
    ports:
      - "80:80"
  e2e:
    container_name: e2e
    build:
      context: .
      dockerfile: Dockerfile
      target: run-e2e
    environment:
      - WEB_HOST=http://web:80
    depends_on: ["web"]
    entrypoint: ["./src/scripts/wait-for-it.sh", "-s", "web:80", "--", "./src/scripts/run-all-tests-docker.sh"]

networks:
  default:
    name: learn-spring-network