singapore-aws-provider = "ap-southeast-1"
singapore-aws-provider-az-a= "ap-southeast-1a"
singapore-aws-provider-az-b= "ap-southeast-1b"
domain_name="tempdomain.in"
subdomain = ""
virginia-aws-provider = "us-east-1"
